# Generated by Django 3.0 on 2022-11-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentasporcobrar',
            old_name='monto_acuenta',
            new_name='monto_devuelto',
        ),
        migrations.RenameField(
            model_name='cuentasporcobrar',
            old_name='monto_porcobrar',
            new_name='monto_entregado',
        ),
    ]
