# Generated by Django 3.0 on 2022-12-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0002_auto_20221115_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentasporcobrar',
            name='monto_entregado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto por cobrar'),
        ),
        migrations.AlterField(
            model_name='detallearqueo',
            name='creado_en',
            field=models.DateTimeField(verbose_name='Detalle arqueo Creacion'),
        ),
        migrations.AlterField(
            model_name='transaccioninventario',
            name='monto_salida',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Salida'),
        ),
    ]
