# Generated by Django 3.0 on 2022-11-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='creado_en',
            field=models.DateTimeField(verbose_name='Fecha de creacion'),
        ),
    ]
